startup_apps:
  - command: cosmic-alternative-startup
    restart_on_death: false
    in_systemd_scope: false
terminal: cosmic-term
custom_actions:
  - command: cosmic-launcher
    action: down
    modifiers:
      - primary
    key: KEY_D
  - command: cosmic-app-library
    action: down
    modifiers:
      - primary
      - shift
    key: KEY_D
