name: Lon

on:
  schedule:
    - cron: "0 12 * * 1-5"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v6

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: drakon64
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Nix shell
        run: nix-shell -A lon --run "exit"

      - name: Evaluate with current lockfile
        run: |
          echo "CURRENT_ISO_HASH=$(nix eval --file default.nix --raw iso -I nixos-config=nixos/iso.nix)" >> "$GITHUB_ENV"
          echo "CURRENT_VIRTUALBOX_HASH=$(nix eval --file default.nix --raw image -I nixos-config=nixos/virtualbox.nix)" >> "$GITHUB_ENV"

      - name: Update Lon lockfile
        run: nix-shell -A lon --run "lon update"

      - name: Evaluate with updated lockfile
        run: |
          echo "NEW_ISO_HASH=$(nix eval --expr '(import ./default.nix {}).iso' -I nixos-config=nixos/iso.nix --raw --impure)" >> "$GITHUB_ENV"
          echo "NEW_VIRTUALBOX_HASH=$(nix eval --expr '(import ./default.nix {}).image' -I nixos-config=nixos/virtualbox.nix --raw --impure)" >> "$GITHUB_ENV"

      - name: Open pull request
        run: |
          git checkout lon.lock
          nix-shell -A lon --run "lon bot github"
        env:
          LON_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LON_LABELS: "lon,bot"
        if: ${{ env.NEW_ISO_HASH != env.CURRENT_ISO_HASH || env.NEW_VIRTUALBOX_HASH != env.CURRENT_VIRTUALBOX_HASH }}
